<a href="https://colab.research.google.com/github/VishalChoudhari2003/Python/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [9]:
lst=[1,2,3,4,5]
arr=np.array(lst)
arr.shape


(5,)

In [11]:
arr[3]

4

In [13]:
arr[3]=7
arr


array([1, 2, 3, 7, 5])

In [14]:
arr[::-1]

array([5, 7, 3, 2, 1])

In [7]:
#2D array
lst1=[1,2,3,4,5,6]
lst2=[7,8,9,10,11,12]
arr1=np.array([lst1,lst2])

In [8]:
arr1.shape


(2, 6)

In [19]:
arr1[:,2:4]


array([[ 3,  4],
       [ 9, 10]])

In [20]:
arr1[:1,:3]

array([[1, 2, 3]])

In [22]:
##EDA
arr1[arr1<2]

array([1])

In [23]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
##Mechanism to create array
np.arange(1,30,3).reshape(10,1)

array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16],
       [19],
       [22],
       [25],
       [28]])

In [34]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.random.rand(3,3)

array([[0.86257564, 0.95379647, 0.93887032],
       [0.82191917, 0.23327868, 0.91740692],
       [0.45188086, 0.440753  , 0.74970937]])