<a href="https://colab.research.google.com/github/VishalChoudhari2003/Python/blob/main/Pandas_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pandas

In [2]:
import pandas as pd
import numpy as np

In [4]:
data=np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
##Dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2','Column3','Column4'])

In [8]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [11]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [12]:
##Indexing
#columnname,rowindex[loc],rowindex columnindex[.iloc]
df[['Column1','Column2']] ## columnname


Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [16]:
df.loc[['Row3','Row4']] ## rowindex

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [17]:
df.iloc[2:4,0:2] ## rowindex columnindex

Column1  Column2
Row3        8        9
Row4       12       13

In [18]:
df.iloc[0:2,2:4]

Column3  Column4
Row1        2        3
Row2        6        7

In [19]:
##convert dataframe into aRRAY
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
##Basic Operations
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [21]:
df['Column2'].value_counts()

Column2
1     1
5     1
9     1
13    1
17    1
Name: count, dtype: int64

In [22]:
df['Column2'].unique()

array([ 1,  5,  9, 13, 17])

In [23]:
df[df['Column2']>2]

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19